builds:
  - id: kurt
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags: -s -w
      -X kurt/internal/version.version={{.Version}}
      -X kurt/internal/version.gitSHA={{.Commit}}
      -X kurt/internal/version.buildTime={{.Date}}
      -extldflags "-static"
checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
sboms: # https://goreleaser.com/customization/sbom/
  - artifacts: archive
archives:
  - id: kurt
    builds:
      - kurt
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"